require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('../models/Question');

const questions = [
  { subject: 'ML', correctOptionId: 'B', questionText: 'What does the term "overfitting" mean in machine learning?', options: [{ id: 'A', text: 'Model performs poorly on training data' }, { id: 'B', text: 'Model performs well on training data but poorly on new data' }, { id: 'C', text: 'Model has too few parameters' }, { id: 'D', text: 'Model ignores the training data entirely' }] },
  { subject: 'ML', correctOptionId: 'A', questionText: 'Which algorithm is a type of supervised learning?', options: [{ id: 'A', text: 'Linear Regression' }, { id: 'B', text: 'K-Means Clustering' }, { id: 'C', text: 'DBSCAN' }, { id: 'D', text: 'Principal Component Analysis' }] },
  { subject: 'ML', correctOptionId: 'C', questionText: 'What is the purpose of a validation set?', options: [{ id: 'A', text: 'To train the model weights' }, { id: 'B', text: 'To evaluate final model performance' }, { id: 'C', text: 'To tune hyperparameters and prevent overfitting' }, { id: 'D', text: 'To augment training data' }] },
  { subject: 'ML', correctOptionId: 'A', questionText: 'Which optimization algorithm is commonly used to minimize loss in neural networks?', options: [{ id: 'A', text: 'Gradient Descent' }, { id: 'B', text: 'Breadth-First Search' }, { id: 'C', text: 'Dijkstra’s Algorithm' }, { id: 'D', text: 'Merge Sort' }] },
  { subject: 'ML', correctOptionId: 'D', questionText: 'Which activation function is most commonly used in hidden layers of deep neural networks?', options: [{ id: 'A', text: 'Sigmoid' }, { id: 'B', text: 'Tanh' }, { id: 'C', text: 'ReLU' }, { id: 'D', text: 'ReLU' }] },
  { subject: 'ML', correctOptionId: 'C', questionText: 'A confusion matrix is primarily used to evaluate:', options: [{ id: 'A', text: 'Model training time' }, { id: 'B', text: 'Feature importance' }, { id: 'C', text: 'Classification performance' }, { id: 'D', text: 'Data normalization' }] },
  { subject: 'ML', correctOptionId: 'B', questionText: 'Which metric focuses on how many predicted positives are actually positive?', options: [{ id: 'A', text: 'Recall' }, { id: 'B', text: 'Precision' }, { id: 'C', text: 'Accuracy' }, { id: 'D', text: 'F-score' }] },
  { subject: 'ML', correctOptionId: 'A', questionText: 'Which model is typically built using an ensemble of decision trees?', options: [{ id: 'A', text: 'Random Forest' }, { id: 'B', text: 'Naive Bayes' }, { id: 'C', text: 'KNN' }, { id: 'D', text: 'PCA' }] },
  { subject: 'ML', correctOptionId: 'C', questionText: 'What is the main goal of the SVM algorithm?', options: [{ id: 'A', text: 'Reduce the number of features' }, { id: 'B', text: 'Cluster unlabeled data' }, { id: 'C', text: 'Find a hyperplane that maximizes the margin between classes' }, { id: 'D', text: 'Generate random samples for augmentation' }] },
  { subject: 'ML', correctOptionId: 'B', questionText: 'In a neural network, backpropagation is used to:', options: [{ id: 'A', text: 'Initialize weights randomly' }, { id: 'B', text: 'Update weights by propagating error gradients backward' }, { id: 'C', text: 'Compress input features' }, { id: 'D', text: 'Select the best activation function' }] },
  { subject: 'ML', correctOptionId: 'A', questionText: 'Which concept describes the tradeoff between bias and variance?', options: [{ id: 'A', text: 'Bias-variance tradeoff' }, { id: 'B', text: 'Regularization bias' }, { id: 'C', text: 'Loss minimization' }, { id: 'D', text: 'Feature sparsity' }] },
  { subject: 'ML', correctOptionId: 'D', questionText: 'L1 and L2 regularization are used mainly to:', options: [{ id: 'A', text: 'Impute missing values' }, { id: 'B', text: 'Scale labels' }, { id: 'C', text: 'Increase training speed' }, { id: 'D', text: 'Reduce overfitting by penalizing large weights' }] },
  { subject: 'ML', correctOptionId: 'B', questionText: 'In k-nearest neighbors, the value of k affects:', options: [{ id: 'A', text: 'GPU memory usage only' }, { id: 'B', text: 'Model sensitivity to noise and decision boundary smoothness' }, { id: 'C', text: 'The number of layers in the network' }, { id: 'D', text: 'The loss function' }] },
  { subject: 'ML', correctOptionId: 'C', questionText: 'Which model is typically easier to interpret due to its tree-like structure?', options: [{ id: 'A', text: 'Decision Tree' }, { id: 'B', text: 'K-Means' }, { id: 'C', text: 'Decision Tree' }, { id: 'D', text: 'Neural Network' }] },
  { subject: 'ML', correctOptionId: 'B', questionText: 'Cross-validation is mainly used to:', options: [{ id: 'A', text: 'Generate more data points' }, { id: 'B', text: 'Estimate generalization performance more reliably' }, { id: 'C', text: 'Train on the full dataset' }, { id: 'D', text: 'Build cloud infrastructure' }] },
  { subject: 'ML', correctOptionId: 'A', questionText: 'Feature scaling is especially important for algorithms that use distance metrics such as:', options: [{ id: 'A', text: 'KNN and SVM' }, { id: 'B', text: 'Naive Bayes only' }, { id: 'C', text: 'Decision Trees only' }, { id: 'D', text: 'Any tree-based model' }] },
  { subject: 'ML', correctOptionId: 'C', questionText: 'Which loss function is most commonly used for binary classification?', options: [{ id: 'A', text: 'MSE' }, { id: 'B', text: 'Huber Loss' }, { id: 'C', text: 'Binary Cross-Entropy' }, { id: 'D', text: 'MAE' }] },
  { subject: 'ML', correctOptionId: 'D', questionText: 'What is a key characteristic of a CNN?', options: [{ id: 'A', text: 'It always uses a linear kernel' }, { id: 'B', text: 'It is only used for text data' }, { id: 'C', text: 'It cannot be trained end-to-end' }, { id: 'D', text: 'It uses convolutional layers to detect patterns in spatial data' }] },
  { subject: 'ML', correctOptionId: 'A', questionText: 'Which statement best distinguishes supervised from unsupervised learning?', options: [{ id: 'A', text: 'Supervised learning uses labeled data, while unsupervised learning uses unlabeled data' }, { id: 'B', text: 'Unsupervised learning always uses regression' }, { id: 'C', text: 'Supervised learning ignores labels' }, { id: 'D', text: 'Both use the same algorithms' }] },
  { subject: 'ML', correctOptionId: 'B', questionText: 'Transfer learning is useful because it:', options: [{ id: 'A', text: 'Guarantees perfect accuracy' }, { id: 'B', text: 'Allows models trained on one task to adapt to another with less data' }, { id: 'C', text: 'Prevents any model from overfitting' }, { id: 'D', text: 'Eliminates the need for validation data' }] },
  { subject: 'MERN', correctOptionId: 'B', questionText: 'What is the primary risk of omitting the dependency array in React\'s useEffect hook?', options: [{ id: 'A', text: 'The effect runs only once when component mounts' }, { id: 'B', text: 'The effect triggers on every render cycle, risking infinite loops' }, { id: 'C', text: 'React throws a syntax error during compilation' }, { id: 'D', text: 'The cleanup function executes before the effect' }] },
  { subject: 'MERN', correctOptionId: 'D', questionText: 'In Express.js, what does `app.use(express.json())` do?', options: [{ id: 'A', text: 'Serves static JSON files from the public folder' }, { id: 'B', text: 'Converts Express responses to JSON automatically' }, { id: 'C', text: 'Validates that incoming data is valid JSON' }, { id: 'D', text: 'Parses incoming requests with JSON payloads into req.body' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'Which Mongoose method finds a document by its _id field?', options: [{ id: 'A', text: 'Model.findById(id)' }, { id: 'B', text: 'Model.findOne({ id })' }, { id: 'C', text: 'Model.getById(id)' }, { id: 'D', text: 'Model.search(id)' }] },
  { subject: 'MERN', correctOptionId: 'B', questionText: 'In React, what does the useState hook return?', options: [{ id: 'A', text: 'Only a setter function' }, { id: 'B', text: 'A state value and a setter function' }, { id: 'C', text: 'A lifecycle callback' }, { id: 'D', text: 'A route configuration' }] },
  { subject: 'MERN', correctOptionId: 'D', questionText: 'Which React Router feature allows nested route rendering?', options: [{ id: 'A', text: 'useMemo' }, { id: 'B', text: 'createPortal' }, { id: 'C', text: 'useRef' }, { id: 'D', text: 'Routes and nested Routes' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'Which statement best describes props in React?', options: [{ id: 'A', text: 'Props are read-only inputs passed from parent to child' }, { id: 'B', text: 'Props are mutable values maintained inside a child component' }, { id: 'C', text: 'Props are only for class components' }, { id: 'D', text: 'Props are used only for HTTP requests' }] },
  { subject: 'MERN', correctOptionId: 'C', questionText: 'In MongoDB, what does an aggregation pipeline do?', options: [{ id: 'A', text: 'Creates indexes automatically' }, { id: 'B', text: 'Stores BSON documents in the database' }, { id: 'C', text: 'Processes documents through stages like match, group, and sort' }, { id: 'D', text: 'Replaces the schema definition' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'What is the purpose of JWT middleware in Express?', options: [{ id: 'A', text: 'To verify the Authorization token and protect routes' }, { id: 'B', text: 'To send JSON responses' }, { id: 'C', text: 'To connect MongoDB' }, { id: 'D', text: 'To render React components' }] },
  { subject: 'MERN', correctOptionId: 'D', questionText: 'Why is CORS configured in a MERN app?', options: [{ id: 'A', text: 'To optimize MongoDB storage' }, { id: 'B', text: 'To encrypt JWT tokens' }, { id: 'C', text: 'To compile JSX code' }, { id: 'D', text: 'To allow browser requests from a different origin' }] },
  { subject: 'MERN', correctOptionId: 'B', questionText: 'Which syntax is used to handle asynchronous code cleanly in Express and Node.js?', options: [{ id: 'A', text: 'Callbacks only' }, { id: 'B', text: 'async/await with try/catch' }, { id: 'C', text: 'switch statements' }, { id: 'D', text: 'forEach loops only' }] },
  { subject: 'MERN', correctOptionId: 'C', questionText: 'What does Mongoose populate() do?', options: [{ id: 'A', text: 'Deletes a document' }, { id: 'B', text: 'Sets a field to null' }, { id: 'C', text: 'Replaces an ObjectId with the referenced document data' }, { id: 'D', text: 'Creates a new collection' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'React Context is mainly used for:', options: [{ id: 'A', text: 'Sharing state across components without prop drilling' }, { id: 'B', text: 'Improving MongoDB queries' }, { id: 'C', text: 'Making API responses synchronous' }, { id: 'D', text: 'Handling CSS animations' }] },
  { subject: 'MERN', correctOptionId: 'D', questionText: 'What is the purpose of useCallback?', options: [{ id: 'A', text: 'To create async requests' }, { id: 'B', text: 'To store database connections' }, { id: 'C', text: 'To render pages in a router' }, { id: 'D', text: 'To memoize a function so it is stable across renders' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'Which is a key difference between REST and GraphQL?', options: [{ id: 'A', text: 'GraphQL lets clients request only the fields they need' }, { id: 'B', text: 'REST supports only one endpoint' }, { id: 'C', text: 'GraphQL cannot be used with JavaScript' }, { id: 'D', text: 'REST is a database system' }] },
  { subject: 'MERN', correctOptionId: 'B', questionText: 'Which HTTP method is typically used to create a new resource?', options: [{ id: 'A', text: 'GET' }, { id: 'B', text: 'POST' }, { id: 'C', text: 'PATCH' }, { id: 'D', text: 'DELETE' }] },
  { subject: 'MERN', correctOptionId: 'D', questionText: 'What is the benefit of indexing in MongoDB?', options: [{ id: 'A', text: 'It automatically removes duplicates' }, { id: 'B', text: 'It reduces the number of documents stored' }, { id: 'C', text: 'It prevents null values in fields' }, { id: 'D', text: 'It speeds up query performance' }] },
  { subject: 'MERN', correctOptionId: 'C', questionText: 'In a React component, what does the component lifecycle include?', options: [{ id: 'A', text: 'Only cleanup logic' }, { id: 'B', text: 'Only route changes' }, { id: 'C', text: 'Mount, update, and unmount phases' }, { id: 'D', text: 'Only database operations' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'Which of these is a controlled component pattern in React?', options: [{ id: 'A', text: 'Input value is controlled by React state' }, { id: 'B', text: 'Input value is managed by browser only' }, { id: 'C', text: 'The component never updates state' }, { id: 'D', text: 'The input is rendered as a div' }] },
  { subject: 'MERN', correctOptionId: 'B', questionText: 'In Node.js, environment variables are usually loaded from:', options: [{ id: 'A', text: 'A JSON file in src/' }, { id: 'B', text: '.env files via dotenv' }, { id: 'C', text: 'Browser storage' }, { id: 'D', text: 'The HTML head tag' }] },
  { subject: 'MERN', correctOptionId: 'D', questionText: 'What is bcrypt used for in a MERN app?', options: [{ id: 'A', text: 'Compressing images' }, { id: 'B', text: 'Caching database results' }, { id: 'C', text: 'Encrypting HTTP headers' }, { id: 'D', text: 'Hashing and verifying user passwords securely' }] },
  { subject: 'MERN', correctOptionId: 'A', questionText: 'Which pattern is commonly used to return an error response in Express?', options: [{ id: 'A', text: 'next(error) with an error-handling middleware' }, { id: 'B', text: 'using a Promise.resolve() in the route' }, { id: 'C', text: 'console.log only' }, { id: 'D', text: 'document.write()' }] },
  { subject: 'CPP', correctOptionId: 'C', questionText: 'What is a constructor in C++?', options: [{ id: 'A', text: 'A function that destroys objects when they go out of scope' }, { id: 'B', text: 'A special variable that holds object references' }, { id: 'C', text: 'A special member function that initializes a new object' }, { id: 'D', text: 'A function that returns the memory address of an object' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'What is the output of `cout << 5/2;` in C++?', options: [{ id: 'A', text: '2' }, { id: 'B', text: '2.5' }, { id: 'C', text: '3' }, { id: 'D', text: 'Compilation error' }] },
  { subject: 'CPP', correctOptionId: 'D', questionText: 'Which keyword is used to prevent a class from being inherited in C++?', options: [{ id: 'A', text: 'static' }, { id: 'B', text: 'abstract' }, { id: 'C', text: 'private' }, { id: 'D', text: 'final' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'What is the primary purpose of a virtual function?', options: [{ id: 'A', text: 'To allow runtime polymorphism through dynamic dispatch' }, { id: 'B', text: 'To declare an inline variable' }, { id: 'C', text: 'To store static data' }, { id: 'D', text: 'To mark a destructor as final' }] },
  { subject: 'CPP', correctOptionId: 'C', questionText: 'Which feature enables polymorphism in C++?', options: [{ id: 'A', text: 'Templates' }, { id: 'B', text: 'Macros' }, { id: 'C', text: 'Virtual functions' }, { id: 'D', text: 'Namespaces' }] },
  { subject: 'CPP', correctOptionId: 'D', questionText: 'Which statement distinguishes function overloading from overriding?', options: [{ id: 'A', text: 'Overloading uses inheritance and overriding does not' }, { id: 'B', text: 'Overriding hides implementation details, overloading does not' }, { id: 'C', text: 'Overloading requires virtual functions, overriding does not' }, { id: 'D', text: 'Overloading is same name, different parameters; overriding is base/derived same signature' }] },
  { subject: 'CPP', correctOptionId: 'B', questionText: 'What is the key difference between a pointer and a reference in C++?', options: [{ id: 'A', text: 'References can be reassigned to another object while pointers cannot' }, { id: 'B', text: 'A reference cannot be null and must be initialized, whereas a pointer can be null' }, { id: 'C', text: 'Pointers are always const' }, { id: 'D', text: 'References are only used for arrays' }] },
  { subject: 'CPP', correctOptionId: 'C', questionText: 'Which operator is used to allocate memory dynamically in C++?', options: [{ id: 'A', text: 'malloc' }, { id: 'B', text: 'new[]' }, { id: 'C', text: 'new' }, { id: 'D', text: 'alloc' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'Which STL container is best suited to a dynamic array with random access?', options: [{ id: 'A', text: 'vector' }, { id: 'B', text: 'queue' }, { id: 'C', text: 'set' }, { id: 'D', text: 'list' }] },
  { subject: 'CPP', correctOptionId: 'D', questionText: 'Templates in C++ allow you to:', options: [{ id: 'A', text: 'Only create abstract classes' }, { id: 'B', text: 'Hide memory addresses' }, { id: 'C', text: 'Inline every function automatically' }, { id: 'D', text: 'Write generic functions and classes for multiple types' }] },
  { subject: 'CPP', correctOptionId: 'B', questionText: 'What does operator overloading let you do?', options: [{ id: 'A', text: 'Change the language standard' }, { id: 'B', text: 'Define custom behavior for operators with user-defined types' }, { id: 'C', text: 'Restrict memory access' }, { id: 'D', text: 'Compile code without headers' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'A friend function in C++ can access:', options: [{ id: 'A', text: 'Private and protected members of the class' }, { id: 'B', text: 'Only public members' }, { id: 'C', text: 'Only static members' }, { id: 'D', text: 'Only constructors' }] },
  { subject: 'CPP', correctOptionId: 'C', questionText: 'What does the scope resolution operator :: do in C++?', options: [{ id: 'A', text: 'It creates a pointer' }, { id: 'B', text: 'It converts a value to a boolean' }, { id: 'C', text: 'It qualifies a member or namespace with its class or namespace' }, { id: 'D', text: 'It allocates memory on the heap' }] },
  { subject: 'CPP', correctOptionId: 'B', questionText: 'Which class relationship is created by multiple inheritance?', options: [{ id: 'A', text: 'A class can inherit from exactly one parent' }, { id: 'B', text: 'A class can inherit from more than one base class' }, { id: 'C', text: 'A class can inherit only abstract types' }, { id: 'D', text: 'A class can inherit from a template only' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'A destructor is used to:', options: [{ id: 'A', text: 'Release resources held by an object when it is destroyed' }, { id: 'B', text: 'Create a new instance of a class' }, { id: 'C', text: 'Store values in a static variable' }, { id: 'D', text: 'Initialize a reference' }] },
  { subject: 'CPP', correctOptionId: 'D', questionText: 'What is a pure virtual function?', options: [{ id: 'A', text: 'A function that cannot be called under any circumstances' }, { id: 'B', text: 'A function that only exists in templates' }, { id: 'C', text: 'A function that is always inline' }, { id: 'D', text: 'A virtual function with = 0, making the class abstract' }] },
  { subject: 'CPP', correctOptionId: 'C', questionText: 'Which of the following is an abstract class?', options: [{ id: 'A', text: 'A class with only constructors' }, { id: 'B', text: 'A class without methods' }, { id: 'C', text: 'A class containing at least one pure virtual function' }, { id: 'D', text: 'A class with static members only' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'What is the purpose of a copy constructor?', options: [{ id: 'A', text: 'To create a new object as a copy of an existing one' }, { id: 'B', text: 'To free memory allocated on the heap' }, { id: 'C', text: 'To overload the assignment operator' }, { id: 'D', text: 'To declare variables at the namespace level' }] },
  { subject: 'CPP', correctOptionId: 'C', questionText: 'Move semantics are mainly used to:', options: [{ id: 'A', text: 'Hide function calls from the compiler' }, { id: 'B', text: 'Convert all variables to references' }, { id: 'C', text: 'Transfer ownership of resources efficiently without deep copies' }, { id: 'D', text: 'Create immutable variables' }] },
  { subject: 'CPP', correctOptionId: 'B', questionText: 'Which keyword is used to define a namespace in C++?', options: [{ id: 'A', text: 'module' }, { id: 'B', text: 'namespace' }, { id: 'C', text: 'using' }, { id: 'D', text: 'class' }] },
  { subject: 'CPP', correctOptionId: 'A', questionText: 'What does try/catch provide in C++?', options: [{ id: 'A', text: 'Exception handling' }, { id: 'B', text: 'Operator overloading' }, { id: 'C', text: 'Memory management' }, { id: 'D', text: 'Template specialization' }] },
  { subject: 'CPP', correctOptionId: 'D', questionText: 'An inline function is typically used to:', options: [{ id: 'A', text: 'Allocate dynamic memory' }, { id: 'B', text: 'Override a virtual method' }, { id: 'C', text: 'Prevent object instantiation' }, { id: 'D', text: 'Suggest to the compiler to replace calls with the function body for efficiency' }] },
  { subject: 'CPP', correctOptionId: 'B', questionText: 'Which statement is true about static members in a class?', options: [{ id: 'A', text: 'They are created per object instance' }, { id: 'B', text: 'They are shared across all objects of the class' }, { id: 'C', text: 'They cannot be private' }, { id: 'D', text: 'They are always virtual' }] },
];

const seedQuestions = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Question.deleteMany({});
    await Question.insertMany(questions);
    console.log('✅ 60 questions seeded successfully');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedQuestions();
